### ISSUE TITLE
Prevents program from terminating (using Deno)

### ISSUE THREAD

**Issue by ghost** [josephrocca/wasm-image-decoder#2]
Using the code:
```ts
const image = decode((await Deno.readFile('...')).buffer);
console.log(a);
```
doesn't allow the program to terminate, but doesn't freeze the program

**Comment by Mqxx** [comment]
Sounds like a unresolved promise.

**Comment by josephrocca** [comment]
Just tested with deno 1.31.1 and it seems to work fine - please re-open another issue if needed.
