### ISSUE TITLE
Getting an error when trying to decode an image

### ISSUE THREAD

**Issue by Mqxx** [josephrocca/wasm-image-decoder#6]
```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '__wbindgen_add_to_stack_pointer')
        wasm.__wbindgen_add_to_stack_pointer(16);
             ^
    at decode (https://deno.land/x/wasm_image_decoder@v0.0.6/wasm/wasm_image_decoder.js:88:14)
```

```ts
import {decode} from 'https://deno.land/x/wasm_image_decoder@v0.0.6/wasm/wasm_image_decoder.js';

const image = await Deno.readFile( './logo.png' );

const result = decode( image );
console.log( result );
```

**Comment by josephrocca** [comment]
You might need to write `decode(image.buffer)` instead of `decode(image)` because I think decode expects an `ArrayBuffer`.

**Comment by josephrocca** [comment]
This should probably be changed/fixed: https://github.com/josephrocca/wasm-image-decoder/issues/3

**Comment by josephrocca** [comment]
Okay, I'd pushed version 0.0.7 which allows both. Although now that I look closer at your code, it looks like the issue is that you're trying to import something other than mod.js, which isn't supported - feel free to open another issue if you run into problems with mod.js
