### ISSUE TITLE
Uncaught SyntaxError: The requested module does not provide an export named 'decode'

### ISSUE THREAD

**Issue by nietsmmar** [josephrocca/wasm-image-decoder#8]
I am using supabase Edge Functions which is running Deno. 

I got this in my `import_map`:

`"wasmImageDecoder": "https://deno.land/x/wasm_image_decoder@v0.0.7/mod.js"`

Then I import it in my file like this:

`import { decode } from "wasmImageDecoder";`

This leads to this error message:
`Uncaught SyntaxError: The requested module 'wasmImageDecoder' does not provide an export named 'decode'`

**Comment by josephrocca** [comment]
Change `import { decode } from ...` to `import decode from ...` as shown in readme.

Generally you should try to look at code to solve this sort of problem: https://github.com/josephrocca/wasm-image-decoder/blob/main/mod.js
